export default [
  {
    brandNew: true,
    color: ["White"],
    country: "Pakistan",
    description:
      "Nike Air Force 1 One Low Triple Black Leather All Classic Retro CW2288-001 Men's",
    discPrice: 1099,
    identity: 1,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 1200.99,
    productId: "5",
    rating: 4,
    reviews: 3,
    seller: "Nike",
    shippingPrice: 220,
    size: 8,
    sponsored: true,
    stock: 32,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l300_a4b0591c6d.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_70c0f77eeb.jpg",
    ],
    watchers: 342,
  },
  {
    brandNew: true,
    color: ["White"],
    country: "Pakistan",
    description:
      "Nike Air Vapormax 2020 FK Flyknit Summit White Blue Grey CJ6740-100 Men's 9",
    discPrice: 2200,
    identity: 2,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 2450,
    productId: "6",
    rating: 4,
    reviews: 3,
    seller: "Nike",
    shippingPrice: 290,
    size: 8.5,
    sponsored: true,
    stock: 34,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l640_695af9c61d.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l400_d389858e28.jpg",
    ],
    watchers: 424,
  },
  {
    brandNew: true,
    color: ["Black"],
    country: "Pakistan",
    description:
      "Men’s Adidas Air Presto 'Green Strike' Running Shoe Size 13 Black White DJ5143-001",
    discPrice: 1799.99,
    identity: 3,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 1999,
    productId: "7",
    rating: 4,
    reviews: 2,
    seller: "Adidas",
    shippingPrice: 89,
    size: 9,
    sponsored: true,
    stock: 31,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l400_5279806054.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_58eb61548f.png",
    ],
    watchers: 425,
  },
  {
    brandNew: true,
    color: ["Blue"],
    country: "Pakistan",
    description:
      "Adidas Free RN Flyknit 2017 Men's Running Shoes Size 11 Blue Black",
    discPrice: 2900,
    identity: 4,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 3210,
    productId: "8",
    rating: 4,
    reviews: 1,
    seller: "Adidas",
    shippingPrice: 110,
    size: 9.5,
    sponsored: false,
    stock: 55,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_e1d46e4bc5.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_99c3a62649.jpg",
    ],
    watchers: 663,
  },
  {
    brandNew: true,
    color: ["Brown"],
    country: "Pakistan",
    description:
      "Puma Sportswear Air Max 90 Dark Driftwood/ Black Sail/ Light Choc UK10 BNIB",
    discPrice: 4300,
    identity: 5,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 4599,
    productId: "9",
    rating: 5,
    reviews: 5,
    seller: "Puma",
    shippingPrice: 220,
    size: 10,
    sponsored: true,
    stock: 31,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l640_f42a6a201e.png",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l640_85c11fefdb.png",
    ],
    watchers: 425,
  },
  {
    brandNew: true,
    color: ["Red"],
    country: "Pakistan",
    description:
      "Puma Air Vapormax Plus University Red Triple Red Shoes CW6973-600",
    discPrice: 2900,
    identity: 6,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 3100,
    productId: "10",
    rating: 4,
    reviews: 2,
    seller: "Puma",
    shippingPrice: 290,
    size: 10.5,
    sponsored: false,
    stock: 45,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/1_548d077876.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_e6202dacbe.jpg",
    ],
    watchers: 342,
  },
  {
    brandNew: true,
    color: ["Black"],
    country: "Pakistan",
    description:
      "Converse Chuck Taylor All Star CX Shoes Midnight Navy - 172808C",
    discPrice: 700,
    identity: 7,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 899,
    productId: "11",
    rating: 3,
    reviews: 2,
    seller: "Converse",
    shippingPrice: 220,
    size: 11,
    sponsored: false,
    stock: 45,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_8aa60b0cd8.png",
    ],
    watchers: 425,
  },
  {
    brandNew: true,
    color: ["Black"],
    country: "Pakistan",
    description:
      "Converse Chuck Taylor All Star Ultra Lightweight 170832C Men Black/White AMRS288",
    discPrice: 2999.99,
    identity: 8,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 3210,
    productId: "12",
    rating: 5,
    reviews: 1,
    seller: "Converse",
    shippingPrice: 290,
    size: 11.5,
    sponsored: true,
    stock: 45,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_48d70f2350.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/71z_Hmc_N8_Wf_S_AC_UX_500_3961c76905.jpg",
    ],
    watchers: 424,
  },
  {
    brandNew: true,
    color: ["Blue"],
    country: "Pakistan",
    description: "Etude House Dear Darling Water Gel Tint #RD307 - 4.5 g",
    discPrice: 260,
    identity: 25,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 300,
    productId: "29",
    rating: 5,
    reviews: 3,
    seller: "Tints",
    shippingPrice: 20,
    size: 11,
    sponsored: false,
    stock: 45,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_a8b4c7eab8.png",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_2fd0e4494f.png",
    ],
    watchers: 425,
  },
  {
    brandNew: true,
    color: ["Red"],
    country: "Pakistan",
    description: "Laneige Tattoo Lip Tint #No.02 - Cheating Orange 6 g",
    discPrice: 899,
    identity: 26,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 999,
    productId: "30",
    rating: 4,
    reviews: 2,
    seller: "Tints",
    shippingPrice: 220,
    size: 9.5,
    sponsored: true,
    stock: 55,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_01571b9bda.png",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_bfb1e8467f.png",
    ],
    watchers: 424,
  },
  {
    brandNew: true,
    color: ["Golden"],
    country: "Pakistan",
    description: "Missha Super Aqua Peeling Gel 100ml",
    discPrice: 430,
    identity: 27,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 450,
    productId: "31",
    rating: 4,
    reviews: 3,
    seller: "Scrubs",
    shippingPrice: 35,
    size: 11,
    sponsored: false,
    stock: 45,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_44a222636a.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_574a4daa82.jpg",
    ],
    watchers: 663,
  },
  {
    brandNew: true,
    color: ["Brown"],
    country: "Pakistan",
    description:
      "Sulwhasoo White Ginseng Moisture Radiance Refining Shower Mask 120ml Exfoliating",
    discPrice: 1000,
    identity: 28,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 1200,
    productId: "32",
    rating: 3,
    reviews: 1,
    seller: "Scrubs",
    shippingPrice: 110,
    size: 9,
    sponsored: false,
    stock: 31,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_1aa84d0ea7.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_885b25f1d3.png",
    ],
    watchers: 663,
  },
  {
    brandNew: true,
    color: ["White"],
    country: "Pakistan",
    description: "INNISFREE GREEN TEA Seed Serum 80mL 2.7FL Oz K.cosmetics",
    discPrice: 650,
    identity: 29,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 699,
    productId: "33",
    rating: 3,
    reviews: 1,
    seller: "Serums",
    shippingPrice: 110,
    size: 9.5,
    sponsored: true,
    stock: 32,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_d1c9ebcf67.jpg",
    ],
    watchers: 342,
  },
  {
    brandNew: true,
    color: ["Golden"],
    country: "Pakistan",
    description:
      "New DR.JART+ PEPTIDIN Serum Pink Energy 40ml (1.35OZ) Skincare Korea Cosmetics",
    discPrice: 1600,
    identity: 30,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 1999,
    productId: "34",
    rating: 5,
    reviews: 2,
    seller: "Serums",
    shippingPrice: 110,
    size: 8,
    sponsored: false,
    stock: 55,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_34781ecdea.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_2c9c47bac1.jpg",
    ],
    watchers: 663,
  },
  {
    brandNew: true,
    color: ["Brown"],
    country: "Pakistan",
    description: "Etude House Collagen Eye Patch Korea Cosmetics 10 Sheets",
    discPrice: 699,
    identity: 31,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 766,
    productId: "35",
    rating: 3,
    reviews: 5,
    seller: "Masks",
    shippingPrice: 60,
    size: 11,
    sponsored: true,
    stock: 55,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_a32b3f01a7.jpg",
    ],
    watchers: 424,
  },
  {
    brandNew: true,
    color: ["White"],
    country: "Pakistan",
    description:
      "Korean Cosmetic The Face Shop Real Nature Tea Tree Facial Mask Sheet 5pcs",
    discPrice: 1099,
    identity: 32,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 1299,
    productId: "36",
    rating: 4,
    reviews: 1,
    seller: "Masks",
    shippingPrice: 110,
    size: 9,
    sponsored: false,
    stock: 32,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l640_3b61ded5e9.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l640_dc44f233b4.jpg",
    ],
    watchers: 663,
  },
  {
    brandNew: false,
    color: ["off-white"],
    country: "Pakistan",
    description: "Etude House My Lash Serum 18g",
    discPrice: 50,
    identity: 57,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 600,
    productId: "61",
    rating: 5,
    reviews: 20,
    seller: "Serum",
    shippingPrice: 150,
    size: 0,
    sponsored: true,
    stock: 2000,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_fbde189e43.jpg",
    ],
    watchers: 1000,
  },
  {
    brandNew: true,
    color: ["vanilla"],
    country: "Pakistan",
    description:
      "20g Deep Hydration Anti-Aging Firming Serum Pure Collagen Cream Skin Care",
    discPrice: 20,
    identity: 58,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 700,
    productId: "62",
    rating: 5,
    reviews: 230,
    seller: "Serum",
    shippingPrice: 30,
    size: 0,
    sponsored: true,
    stock: 2,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_d230c40c14.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_b853cae64a.jpg",
    ],
    watchers: 23,
  },
  {
    brandNew: true,
    color: ["Brown"],
    country: "Pakistan",
    description: "07. BHUTAN 1991 SET/12 STAMP M/S ART BY RUBENS . MNH",
    discPrice: 899,
    identity: 33,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 1000,
    productId: "37",
    rating: 5,
    reviews: 3,
    seller: "Stamps",
    shippingPrice: 110,
    size: 9,
    sponsored: true,
    stock: 34,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_534a85af4a.jpg",
    ],
    watchers: 663,
  },
  {
    brandNew: true,
    color: ["Brown"],
    country: "Pakistan",
    description:
      "107.NEPAL 1971 SET/3 STAMP BHAIRAV SERIES, HINDU MYTHOLOGY FDC",
    discPrice: 3099,
    identity: 34,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 3210,
    productId: "38",
    rating: 4,
    reviews: 5,
    seller: "Stamps",
    shippingPrice: 110,
    size: 11,
    sponsored: false,
    stock: 32,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_70f69dafb6.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_bc25f0e9a8.jpg",
    ],
    watchers: 663,
  },
  {
    brandNew: true,
    color: ["Golden"],
    country: "Pakistan",
    description:
      "🔥 POISON IVY #3 Joshua Middleton Variant - DC Release 08/02/2022 🔥",
    discPrice: 500,
    identity: 35,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 599,
    productId: "39",
    rating: 3,
    reviews: 2,
    seller: "Comics",
    shippingPrice: 89,
    size: 9.5,
    sponsored: false,
    stock: 31,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_099fecf08a.png",
    ],
    watchers: 663,
  },
  {
    brandNew: true,
    color: ["Brown"],
    country: "Pakistan",
    description:
      "The New Adventures of the Toxic Avenger #1 (2000) VG, Brian McNulty, Good Condit",
    discPrice: 899,
    identity: 36,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 910,
    productId: "40",
    rating: 5,
    reviews: 5,
    seller: "Comics",
    shippingPrice: 110,
    size: 9.5,
    sponsored: false,
    stock: 45,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_62bb136afc.jpg",
    ],
    watchers: 425,
  },
  {
    brandNew: true,
    color: ["Golden"],
    country: "Pakistan",
    description:
      "Russia 150 Roubles 1988 1/2 Ounce Platinum, Song of the Journey of Prince Igor",
    discPrice: 1400,
    identity: 37,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 1999,
    productId: "41",
    rating: 4,
    reviews: 5,
    seller: "Coins",
    shippingPrice: 220,
    size: 11,
    sponsored: false,
    stock: 55,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_48b71b5eef.jpg",
    ],
    watchers: 663,
  },
  {
    brandNew: true,
    color: ["White"],
    country: "Pakistan",
    description:
      "Assorted 1 Of 1965 Canada Silver Dollar .800 Silver 23.33 Grams 36 mm Thick",
    discPrice: 1799,
    identity: 38,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 2330,
    productId: "42",
    rating: 4,
    reviews: 3,
    seller: "Coins",
    shippingPrice: 199,
    size: 9,
    sponsored: true,
    stock: 34,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_aaf558d095.jpg",
    ],
    watchers: 425,
  },
  {
    brandNew: true,
    color: ["Golden"],
    country: "Pakistan",
    description:
      "Kingdom of Macedon Alexander III (the Great) AR tetradrachm 336-323 BC",
    discPrice: 1900,
    identity: 39,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 2450,
    productId: "43",
    rating: 4,
    reviews: 5,
    seller: "Antiques",
    shippingPrice: 200,
    size: 8,
    sponsored: false,
    stock: 31,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_2334b1865e.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_fc915cff3f.jpg",
    ],
    watchers: 424,
  },
  {
    brandNew: true,
    color: ["Golden"],
    country: "Pakistan",
    description:
      "Middle Eastern Persian Hand Painted Lacquered Bronze Bowl 18th Century",
    discPrice: 1899,
    identity: 40,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 2100,
    productId: "44",
    rating: 5,
    reviews: 3,
    seller: "Antiques",
    shippingPrice: 209,
    size: 8,
    sponsored: false,
    stock: 45,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_4acaa75bfd.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_22b14e2fea.jpg",
    ],
    watchers: 342,
  },
  {
    brandNew: false,
    color: ["Brown"],
    country: "Pakistan",
    description:
      'Limited Ukraine stamps "Russian warship… DONE!”, F, stamps sheet set',
    discPrice: 80,
    identity: 65,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 100,
    productId: "69",
    rating: 5,
    reviews: 200,
    seller: "Stamps",
    shippingPrice: 20,
    size: 4,
    sponsored: true,
    stock: 200,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_ef3b2b2ece.png",
    ],
    watchers: 199,
  },
  {
    brandNew: false,
    color: ["Yellow"],
    country: "Pakistan",
    description:
      'PRESALE! UKRAINE 2022 - "Good Evening, We Are From Ukraine" Stamps sheet "F"',
    discPrice: 150,
    identity: 66,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 200,
    productId: "70",
    rating: 5,
    reviews: 29,
    seller: "Stamps",
    shippingPrice: 30,
    size: 5,
    sponsored: true,
    stock: 20,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_020d9050b1.jpg",
    ],
    watchers: 5,
  },
  {
    brandNew: true,
    color: ["Black"],
    country: "Pakistan",
    description:
      "Fashion Sport Men's Stainless Steel Case Leather Band Quartz Analog Wrist Watch",
    discPrice: 2800,
    identity: 9,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 3210,
    productId: "13",
    rating: 5,
    reviews: 1,
    seller: "Casio",
    shippingPrice: 220,
    size: 8,
    sponsored: true,
    stock: 45,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/8ee11ddd86035045c0d5e9762b63cbb0_75bdce68b7.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/bcb5b0067103025bcaa790bf8c0e47cf_04241042c1.jpg",
    ],
    watchers: 424,
  },
  {
    brandNew: true,
    color: ["Golden"],
    country: "Pakistan",
    description:
      "Men's Watch Mesh Belt Business Minimalist Ultra Thin Watches Stainless Steel NEW",
    discPrice: 1999,
    identity: 10,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 2100,
    productId: "14",
    rating: 3,
    reviews: 1,
    seller: "Casio",
    shippingPrice: 110,
    size: 9,
    sponsored: false,
    stock: 32,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/ba6d5974a1281166e41b444c0455839e_86680f9485.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/bf09182ea15d4ad1085a0eaec4d8277a_71365a4ecb.jpg",
    ],
    watchers: 425,
  },
  {
    brandNew: true,
    color: ["Golden"],
    country: "Pakistan",
    description:
      "Invicta Pro Diver 20281 Men's Round Analog Chronograph Date Polyurethane Watch",
    discPrice: 800,
    identity: 11,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 999,
    productId: "15",
    rating: 5,
    reviews: 3,
    seller: "Tissot",
    shippingPrice: 110,
    size: 8.5,
    sponsored: false,
    stock: 55,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l1600_422ad43afc.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l640_9a48325657.jpg",
    ],
    watchers: 424,
  },
  {
    brandNew: true,
    color: ["Brown"],
    country: "Pakistan",
    description:
      "PRE OWNED SEIKO DIVER 7002-7000 OCEAN SHARK AUTOMATIC MENS WATCH 492911",
    discPrice: 2000,
    identity: 12,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 2200,
    productId: "16",
    rating: 5,
    reviews: 1,
    seller: "Tissot",
    shippingPrice: 110,
    size: 9.5,
    sponsored: false,
    stock: 55,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_c53077558e.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_4d0d8acbe7.jpg",
    ],
    watchers: 342,
  },
  {
    brandNew: true,
    color: ["Blue"],
    country: "Pakistan",
    description:
      "Citizen 1853 Chronograph Black Dial Quartz Wrist Watch For Men",
    discPrice: 1600,
    identity: 13,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 1899,
    productId: "17",
    rating: 5,
    reviews: 3,
    seller: "Citizen",
    shippingPrice: 200,
    size: 11,
    sponsored: true,
    stock: 32,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_cdcd787540.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_ca83ef2e81.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_1b9b3e6b0f.jpg",
    ],
    watchers: 425,
  },
  {
    brandNew: true,
    color: ["Black"],
    country: "Pakistan",
    description: "CitizenT-Sport Men's Black Watch - T106.427.16.051.00",
    discPrice: 4300,
    identity: 14,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 4599,
    productId: "18",
    rating: 3,
    reviews: 5,
    seller: "Citizen",
    shippingPrice: 290,
    size: 11,
    sponsored: false,
    stock: 31,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l640_9de4f06ff5.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l640_230bc18e50.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l640_832bbd7253.jpg",
    ],
    watchers: 342,
  },
  {
    brandNew: true,
    color: ["Black"],
    country: "Pakistan",
    description: "Seiko Prospex Orange Men's Rubber Strap Watch - SKX011",
    discPrice: 1600,
    identity: 15,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 1870,
    productId: "19",
    rating: 3,
    reviews: 2,
    seller: "Swatch",
    shippingPrice: 100,
    size: 9,
    sponsored: true,
    stock: 55,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_bdc05501bd.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_438de0378f.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_b4bb00e030.jpg",
    ],
    watchers: 345,
  },
  {
    brandNew: true,
    color: ["Blue"],
    country: "Pakistan",
    description:
      "Swatch Orologio G-shock Gbd-h1000-7a9er G-squad GPS Solare Cardio da polso Bianco",
    discPrice: 1650,
    identity: 16,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 1999,
    productId: "20",
    rating: 3,
    reviews: 5,
    seller: "Swatch",
    shippingPrice: 89,
    size: 8.5,
    sponsored: false,
    stock: 32,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l640_1033b3dd14.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l640_6ad3f31cfb.jpg",
    ],
    watchers: 425,
  },
  {
    brandNew: true,
    color: ["White"],
    country: "Pakistan",
    description: "Shimano EXPRIDE 166ML Baitcasting Rod for Bass",
    discPrice: 299,
    identity: 41,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 307,
    productId: "45",
    rating: 5,
    reviews: 5,
    seller: "Rods",
    shippingPrice: 29,
    size: 8,
    sponsored: true,
    stock: 34,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_f97cef7922.jpg",
    ],
    watchers: 342,
  },
  {
    brandNew: true,
    color: ["White"],
    country: "Pakistan",
    description: "Major Craft Aji-Do 5G AD5-S682M/AJI Spinning Rod",
    discPrice: 229,
    identity: 42,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 334,
    productId: "46",
    rating: 5,
    reviews: 5,
    seller: "Rods",
    shippingPrice: 34,
    size: 8,
    sponsored: true,
    stock: 4,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_d64b8d952c.jpg",
    ],
    watchers: 425,
  },
  {
    brandNew: true,
    color: ["Black"],
    country: "Pakistan",
    description:
      "Simrad GO12 XSE Marine GPS with Active Imaging 3-in-1 Transducer 000-14834-002",
    discPrice: 799,
    identity: 43,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 999,
    productId: "47",
    rating: 4,
    reviews: 3,
    seller: "Fishfinders",
    shippingPrice: 110,
    size: 8,
    sponsored: true,
    stock: 45,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_72a4ac859e.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_0a255a86a1.jpg",
    ],
    watchers: 342,
  },
  {
    brandNew: true,
    color: ["Black"],
    country: "Pakistan",
    description:
      "Garmin STRIKER Plus 4 Fishfinder with Dual Beam Transducer 010-01870-00",
    discPrice: 100,
    identity: 44,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 139,
    productId: "48",
    rating: 5,
    reviews: 3,
    seller: "Fishfinders",
    shippingPrice: 25,
    size: 8.5,
    sponsored: false,
    stock: 45,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_20b76c5c03.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_922064449b.jpg",
    ],
    watchers: 425,
  },
  {
    brandNew: true,
    color: ["Black"],
    country: "Pakistan",
    description:
      "Anaconda Fish Hawk GTM Water Thermometer Carp Fishing Feeders Catfish Fishing NEW",
    discPrice: 670,
    identity: 45,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 999,
    productId: "49",
    rating: 4,
    reviews: 1,
    seller: "Equipment ",
    shippingPrice: 220,
    size: 8.5,
    sponsored: false,
    stock: 45,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_c7b50dbbee.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_fd982165d5.jpg",
    ],
    watchers: 663,
  },
  {
    brandNew: true,
    color: ["Black"],
    country: "Pakistan",
    description:
      "Lumica Ikejime Fish Nerve Tightening Wire Set Medium 60cm Brain Spike Tool Blue",
    discPrice: 240,
    identity: 46,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 250.99,
    productId: "50",
    rating: 3,
    reviews: 5,
    seller: "Equipment ",
    shippingPrice: 89,
    size: 10,
    sponsored: false,
    stock: 32,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_517ef78341.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_10bd152ef1.jpg",
    ],
    watchers: 342,
  },
  {
    brandNew: true,
    color: ["Golden"],
    country: "Pakistan",
    description: "Shimano 21 TWIN POWER SW 14000PG Spinning Reel",
    discPrice: 600,
    identity: 47,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 670,
    productId: "51",
    rating: 4,
    reviews: 2,
    seller: "Reels",
    shippingPrice: 89,
    size: 9,
    sponsored: true,
    stock: 45,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_279efc9d17.jpg",
    ],
    watchers: 663,
  },
  {
    brandNew: true,
    color: ["Golden"],
    country: "Pakistan",
    description:
      "Allen Kraken #4 9wt-11wt Fly Reel loaded with line and backing",
    discPrice: 1299,
    identity: 48,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 1499,
    productId: "52",
    rating: 3,
    reviews: 3,
    seller: "Reels",
    shippingPrice: 100,
    size: 8.5,
    sponsored: false,
    stock: 44,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_9bf44e6f4b.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_b34376539a.jpg",
    ],
    watchers: 663,
  },
  {
    brandNew: true,
    color: ["Golden"],
    country: "Pakistan",
    description:
      "Samsung Galaxy S22 Ultra SM-S908U - 512GB - Phantom Black (Unlocked)",
    discPrice: 3100,
    identity: 17,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 3210,
    productId: "21",
    rating: 5,
    reviews: 5,
    seller: "Samsung",
    shippingPrice: 220,
    size: 8.5,
    sponsored: true,
    stock: 31,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l640_65116960ba.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l640_137624f5c8.jpg",
    ],
    watchers: 424,
  },
  {
    brandNew: true,
    color: ["Golden"],
    country: "Pakistan",
    description:
      "Samsung Galaxy S22 Ultra SM-S908B/DS - 1TB - Burgundy (Unlocked) bundle",
    discPrice: 4300,
    identity: 18,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 4500,
    productId: "22",
    rating: 4,
    reviews: 3,
    seller: "Samsung",
    shippingPrice: 100,
    size: 9.5,
    sponsored: false,
    stock: 31,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_1212370ba6.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_063c70623b.jpg",
    ],
    watchers: 342,
  },
  {
    brandNew: true,
    color: ["Black"],
    country: "Pakistan",
    description:
      "Apple iPhone 12 Pro Max, 256GB, Pacific Blue - Unlocked (Renewed Premium)",
    discPrice: 4399,
    identity: 19,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 4450,
    productId: "23",
    rating: 4,
    reviews: 5,
    seller: "Apple",
    shippingPrice: 110,
    size: 9,
    sponsored: false,
    stock: 55,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/71_Fu_I8_Yv_CNL_AC_SX_466_9e9ed2f64d.jpg",
    ],
    watchers: 425,
  },
  {
    brandNew: true,
    color: ["White"],
    country: "Pakistan",
    description:
      "Apple iPhone 11 [64GB, Purple] + Carrier Subscription [Cricket Wireless]",
    discPrice: 5320,
    identity: 20,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 5500,
    productId: "24",
    rating: 5,
    reviews: 1,
    seller: "Apple",
    shippingPrice: 290,
    size: 10,
    sponsored: true,
    stock: 55,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/71xn9b_C_Rfh_L_F_Mwebp_c305bdb883.jpg",
    ],
    watchers: 425,
  },
  {
    brandNew: true,
    color: ["Black"],
    country: "Pakistan",
    description:
      'Xiaomi Redmi Note 9 Pro Smartphone - 6.67" DotDisplay,6 GB + 128 GB, 64 MP AI Quad Camera, 5020 mAh (type) NFC, Grigio (Interstellar Grey)',
    discPrice: 3000,
    identity: 21,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 3210,
    productId: "25",
    rating: 5,
    reviews: 5,
    seller: "Xiomi",
    shippingPrice: 110,
    size: 11,
    sponsored: true,
    stock: 32,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/811_Hp_E2_Z_Wx_L_AC_SY_679_c4c9b786e3.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/81_G_Cx_HA_7_J2_L_AC_SY_679_aa4fb173fb.jpg",
    ],
    watchers: 663,
  },
  {
    brandNew: true,
    color: ["Black"],
    country: "Pakistan",
    description: "Redmi 10 Prime 2022 (Phantom Black, 4GB RAM, 64GB Storage)",
    discPrice: 1750,
    identity: 22,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 1800,
    productId: "26",
    rating: 4,
    reviews: 5,
    seller: "Xiomi",
    shippingPrice: 220,
    size: 9,
    sponsored: false,
    stock: 32,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/71jo_AQ_6o_EWL_SX_679_63cf5e0de0.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/71_Noa6_L_Fi_OL_SX_679_95d35ed2ad.jpg",
    ],
    watchers: 345,
  },
  {
    brandNew: true,
    color: ["White"],
    country: "Pakistan",
    description:
      "Moto G fast | 2020 | Unlocked | Made for US by Motorola | 3/32GB | 16MP Camera | White",
    discPrice: 800,
    identity: 23,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 999,
    productId: "27",
    rating: 4,
    reviews: 3,
    seller: "Motorola",
    shippingPrice: 50,
    size: 9.5,
    sponsored: false,
    stock: 55,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/81_O2f_X_Sl_HCL_AC_SX_466_9731a1a928.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/71_GCB_Zq_Jjn_L_AC_SX_466_c7ab0a9b2c.jpg",
    ],
    watchers: 342,
  },
  {
    brandNew: true,
    color: ["Blue"],
    country: "Pakistan",
    description:
      "total wireless Motorola Moto g Power (2021), 64GB, Dark Grove - Prepaid Smartphone (Locked)",
    discPrice: 1600,
    identity: 24,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 1999,
    productId: "28",
    rating: 5,
    reviews: 1,
    seller: "Motorola",
    shippingPrice: 110,
    size: 8,
    sponsored: true,
    stock: 32,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/71z_Grr_Ae5_NL_AC_SX_466_8c74de4367.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/71_URKNG_6_PVL_AC_SX_466_d1c963c662.jpg",
    ],
    watchers: 342,
  },
  {
    brandNew: true,
    color: ["White", "Black"],
    country: "Pakistan",
    description: "BRAND NEW UNOPENED SAMSUNG A32 5G BLACK",
    discPrice: 50,
    identity: 49,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 200,
    productId: "53",
    rating: 5,
    reviews: 2,
    seller: "Samsung",
    shippingPrice: 15,
    size: 5,
    sponsored: true,
    stock: 22,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_1adc797ece.jpg",
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l500_1b5b6f4872.jpg",
    ],
    watchers: 28,
  },
  {
    brandNew: true,
    color: ["Grey"],
    country: "Pakistan",
    description: "SAMSUNG Galaxy J1 SM-J100Y - 4GB - White Smartphone",
    discPrice: 200,
    identity: 50,
    listedDate: "October 13, 2012 11:13:00",
    orgPrice: 3000,
    productId: "54",
    rating: 3,
    reviews: 100,
    seller: "Samsung",
    shippingPrice: 100,
    size: 7,
    sponsored: false,
    stock: 100,
    uri: [
      "https://ebay-clone-backend.herokuapp.com/uploads/s_l600_102899f71b.jpg",
    ],
    watchers: 22,
  },
];
